### ISSUE TITLE
Is there a way to disable click for next page

### ISSUE THREAD

**Issue by miish3lov** [luejerry/html-mangareader#11]
Whenever I scroll I sometimes accidently click the screen which results moving to the next image, Is there a way to disable this feature?

**Comment by luejerry** [comment]
Added in [v2.2.0](https://github.com/luejerry/html-mangareader/releases/tag/v2.2.0)

**Comment by myarcana** [comment]
https://github.com/luejerry/html-mangareader?tab=readme-ov-file#configini-options

Is there a way to set `disableNavBar = yes` in a version of the app downloaded from Releases? (As opposed to one built locally)

**Comment by myarcana** [comment]
You have to update config.ini to make `disableNavButtons = yes`

Windows  `%LOCALAPPDATA%\html-mangareader\config.ini`
MacOS `~/Library/Application Support/html-mangareader/config.ini`

https://github.com/luejerry/html-mangareader?tab=readme-ov-file#configini-options



    sed -i '' 's/^disableNavButtons = .*/disableNavButtons = yes/' ~/Library/Application\ Support/html-mangareader/config.ini
