### ISSUE TITLE
Building on macOS fails (x86_64)

### ISSUE THREAD

**Issue by frykauf** [luejerry/html-mangareader#12]
It seems I was able to solve issue with rarfile by changing 
"from rarfile import rarfile" into "from mangareader.rarfile import RarFile"
and adding rarfile.py into the mangareader folder.

But there seems to also be an issue with importing Py7zr which with my limited knowledge I was unable to solve. (I'm not a programmer): "from py7zr import py7zr"

both are from mangarenderer.py

but there is also issue in reader.py with "from mangareader.mangarender import extract_render"

This is the whole error (after fixing the issue with rarfile):
`
Traceback (most recent call last):
  File "reader.py", line 7, in <module>
    from mangareader.mangarender import extract_render
  File "/Users/Martiu/Downloads/html-mangareader-master/mangareader/mangarender.py", line 6, in <module>
    from py7zr import py7zr
ModuleNotFoundError: No module named 'py7zr'
`

**Comment by luejerry** [comment]
Make sure to run `pip install -r requirements.txt` first
