### ISSUE TITLE
Open multiple files?

### ISSUE THREAD

**Issue by jamedom** [luejerry/html-mangareader#13]
Hello, I really love this app but is there a way to open multiple files or all files in folder? because I don't want to open it one by one when finished reading. Thankyou.

**Comment by Aniconomics** [comment]
I'm Wondering the same thing, it would be cool if i just click next and i would be taken to the next chapter in my file directory

**Comment by luejerry** [comment]
I've looked into adding this feature but unfortunately it's not really possible due to browser security restrictions that restrict access to the filesystem. The app would need to be converted to use something like Electron, which I'm trying to avoid with this app. Sorry!
