### ISSUE TITLE
PDF ?

### ISSUE THREAD

**Issue by omaru-ok** [luejerry/html-mangareader#16]
any PDF or documant reader like this?

**Comment by omaru-ok** [comment]
btw, that reader is damn gold thigns  🤯

**Comment by luejerry** [comment]
Sorry, PDF support is an entirely different beast which I'm not planning on doing. I would suggest using a PDF specific app or simply your browser's built in PDF viewer.

**Comment by omaru-ok** [comment]
> Sorry, PDF support is an entirely different beast which I'm not planning on doing. I would suggest using a PDF specific app or simply your browser's built in PDF viewer.

okay 👍
