### ISSUE TITLE
Add support for .webp images

### ISSUE THREAD

**Issue by whalehub** [luejerry/html-mangareader#3]
If you try to open a .cbz/.cbr file that contains .webp images with this tool, you currently get an error message which says "No image files were found in archive".

The WEBP image format is supported by all [modern browsers](https://caniuse.com/#search=webp), so I think that a tool which utilizes a browser to read .cbz/.cbr files should support them as well.

**Comment by luejerry** [comment]
Thanks for the suggestion. Webp will be enabled as part of the next release, coming very soon :)

**Comment by whalehub** [comment]
@luejerry Thanks!
