### ISSUE TITLE
[Feature Request] A different mode for webtoons.

### ISSUE THREAD

**Issue by Andrei-Stakov** [luejerry/html-mangareader#4]
IDK if this was already in your planned feature list or not...

_A different css style option for webtoons_; since webtoons already drawn with continuous scrolling flow in mind, the shadow and the gap between the page is honestly quite distracting.

It would also be wonderful if we have a selector for different css styles.

**Comment by luejerry** [comment]
Thanks for the suggestion. I had not thought of this use case but I have been planning a dark mode toggle which would involve similar work to this. I will include it with the next feature release.

**Comment by luejerry** [comment]
Added in [v1.7.0](https://github.com/luejerry/html-mangareader/releases/tag/v1.7.0).

**Comment by whalehub** [comment]
@luejerry Thank you!
