### ISSUE TITLE
[Feature Request] Load next/previous file in the folder

### ISSUE THREAD

**Issue by whalehub** [luejerry/html-mangareader#5]
It would be neat if it was possible to switch to the next/previous .cbz file in the current folder without having to execute mangareader again and selecting it manually in the file explorer.

**Comment by whalehub** [comment]
@luejerry

**Comment by luejerry** [comment]
This is a good idea, will definitely think about how to add this in a future release. Can't promise it'll be coming soon unfortunately, since I'm imagining it might require some pretty significant changes to the basic app architecture.

**Comment by Aniconomics** [comment]
This feature request is closed so I assume it was added in. I downloaded the software on my windows 10 OS and I loaded in a chapter. How do I go to the next chapter listed in the file directory

**Comment by luejerry** [comment]
@Aniconomics This feature was not added, and I've decided to drop it because it would require using a much heavier framework like Electron to implement due to browser security restrictions. Sorry for the confusion.
