### ISSUE TITLE
[Feature Request] Fit to height

### ISSUE THREAD

**Issue by dead-line** [luejerry/html-mangareader#6]
An option to fit to height would be cool.

**Comment by luejerry** [comment]
Thanks for the suggestion. I originally decided not to include this because I wasn't sure there was a use case for it, but it seems like there is. I'll add this to the next release

**Comment by luejerry** [comment]
Added in [v1.8.0](https://github.com/luejerry/html-mangareader/releases/tag/v1.8.0).
